# Generated by Django 2.2 on 2020-08-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_dates_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='app_one.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='people', to='app_one.User'),
            preserve_default=False,
        ),
    ]
