# Generated by Django 2.2 on 2020-08-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_auto_20200806_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='app_one.Person'),
        ),
    ]
