# Generated by Django 2.2 on 2020-08-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_auto_20200806_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
