# Generated by Django 2.2 on 2020-08-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
