# Generated by Django 2.2 on 2020-08-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0008_auto_20200807_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='p_type',
            field=models.CharField(default='', max_length=4),
        ),
    ]
